apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: grpc-lb-example
  name:  grpc-lb-example-greeter-client-envoy-sidecar
  labels:
    name: grpc-lb-example-greeter-client-envoy-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      name: greeter-client-envoy-sidecar
  template:
    metadata:
      labels:
        name: greeter-client-envoy-sidecar
    spec:
      containers:
      - name: greeter-client
        image: harbor.internal.moqi.ai/pingji/java_greeter_client:1.0
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      - name: envoy-proxy 
        image: harbor.internal.moqi.ai/pingji/envoy:v1.22.2
        ports:
        - name: http
          containerPort: 50051
        volumeMounts:
        - name: config
          mountPath: /etc/envoy
      volumes:
      - name: config
        configMap:
          name: envoy-sidecar-config